apiVersion: v1
kind: Secret
metadata:
  name: mandmandm-secrets
  namespace: mandmandm
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://mandmandm:mandmandm@<IP_PRIVADA_DB>:5432/mandmandm"
  MONGO_URI: "mongodb://<IP_PRIVADA_DB>:27017"
  REDIS_URI: "redis://<IP_PRIVADA_DB>:6379/0"
  RABBITMQ_URL: "amqp://chatuser:chatpass@<IP_PRIVADA_DB>:5672/"
  JWT_SECRET: "mandmandm_chat_secret_2026_muy_largo_igual_en_todos"
  OAUTH_GOOGLE_CLIENT_ID: "tu_client_id"
  OAUTH_GOOGLE_CLIENT_SECRET: "tu_client_secret"
